name: Backend Docker Image CI

on:
    push:
        branches: [ "main" ]
        paths:
            - 'Backend/**'  
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker build -t cs4800-studydecks-deployment ./Backend

    - name: Tag the Docker image
      run: docker tag cs4800-studydecks-deployment remrem06/cs4800-studydecks-deployment:latest

    - name: Push the Docker image
      run: docker push remrem06/cs4800-studydecks-deployment:latest
