name: Frontend Docker Image CI

on:
    push:
        branches: [ "main" ]
        paths:
            - 'Frontend/**'  
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker build -t cs-4800-studydecks-frontend ./Frontend

    - name: Tag the Docker image
      run: docker tag cs-4800-studydecks-frontend remrem06/cs-4800-studydecks-frontend:latest

    - name: Push the Docker image
      run: docker push remrem06/cs-4800-studydecks-frontend:latest

    - name: Update Docker image in EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ec2-54-215-75-149.us-west-1.compute.amazonaws.com
        username: ec2-user
        port: 22
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            sudo ./update-frontend-docker.sh
