name: Backend Docker Image CI

on:
    push:
        branches: [ "main" ]
        paths:
            - 'Backend/**'  
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build --build-arg DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
        --build-arg DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
        --build-arg DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
        --build-arg FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
        -t cs4800-studydecks-deployment ./Backend

    - name: Tag the Docker image
      run: docker tag cs4800-studydecks-deployment remrem06/cs4800-studydecks-deployment:latest

    - name: Push the Docker image
      run: docker push remrem06/cs4800-studydecks-deployment:latest

    - name: Update Docker image in EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ec2-54-215-75-149.us-west-1.compute.amazonaws.com
        username: ec2-user
        port: 22
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            sudo ./update-backend-docker.sh
